name: Flat
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      URL:
        description: 'your github repo URL,like https://conoro.github.io/tiktok-rss-flat/'
        type: enviroment
        required: true
      usernames:
        description: 'TikTok usernames you like to rss,if you want more than one ,pls edit subscriptions.csv'
        type: enviroment
        required: true  

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: update apt
        run: sudo apt-get update
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://conoroneill.com/index.xml
          downloaded_filename: conor_rss.xml
          postprocess: postprocess.ts
        env:
          URL: ${{ github.event.inputs.URL }}        
          usernames: ${{ github.event.inputs.usernames }}        
